language: haxe

haxe:
  - "3.4.7"
  - development

matrix:
  allow_failures:
    - haxe: development

script:
  - haxe run.hxml
  - haxe --cwd test build.hxml
  - neko run.n test/app.n
  - ./test/app
